<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    $vendorDir . '/symfony/var-dumper/Symfony/Component/VarDumper/Resources/functions/dump.php',
    $vendorDir . '/nikic/php-parser/lib/bootstrap.php',
    $vendorDir . '/ircmaxell/password-compat/lib/password.php',
    $vendorDir . '/swiftmailer/swiftmailer/lib/swift_required.php',
    $vendorDir . '/paragonie/random_compat/lib/random.php',
    $vendorDir . '/symfony/polyfill-php56/bootstrap.php',
    $vendorDir . '/psy/psysh/src/Psy/functions.php',
    $vendorDir . '/danielstjules/stringy/src/Create.php',
    $vendorDir . '/laravel/framework/src/Illuminate/Foundation/helpers.php',
    $vendorDir . '/laravel/framework/src/Illuminate/Support/helpers.php',
    $vendorDir . '/laravelcollective/html/src/helpers.php',
);
